### ISSUE TITLE
Ability to remove companions

### ISSUE THREAD

**Issue by brylie** [GeriLife/companionship-care#28]
Some companionship relationships may be temporary. As such, the care coordinator may need to remove existing companions.

## Task

- [ ] allow care coordinators to remove existing companions from a person's page

## Specification

- [ ] add a small "remove" button next to each companion on the person's page
- [ ] only organizers can see button/remove companions
- [ ] organizers cannot remove themselves
- [ ] "remove" button links to `CompanionDeleteView`, based on the Django generic [View]() class-based view
- [ ] `CompanionDeleteView` takes only a `post` request
- [ ] `CompanionDeleteView` validates that user one of `Person`'s `organizers` or throws `NotAuthorized` error
- [ ] after deleting companion, for authorized user, the `CompanionDeleteView` post method will redirect to the `PersonDetailView` for the relevant person

## Example code
The following code snippets may be useful as examples related to this task.

Checking if request `User` is one of `Person`'s organizers
https://github.com/GeriLife/companionship-care/blob/d7cdcdc1a37e5bd08f9c7b6a26a8116b9571ce5e/project/people/templates/people/person_detail.html#L104

Preventing a user from removing themself by checking equality (in our case, it should be `!=`)
https://github.com/GeriLife/companionship-care/blob/d7cdcdc1a37e5bd08f9c7b6a26a8116b9571ce5e/project/people/templates/people/person_activity.html#L70

Linking to a specific view, using the view `name` and optional arguments
https://github.com/GeriLife/companionship-care/blob/d7cdcdc1a37e5bd08f9c7b6a26a8116b9571ce5e/project/people/templates/people/person_detail.html#L130-L132

Ensuring only a `Person`'s organizer can perform database operations related to that person
https://github.com/GeriLife/companionship-care/blob/d7cdcdc1a37e5bd08f9c7b6a26a8116b9571ce5e/project/people/views.py#L130-L137

Redirect to `Person`'s detail view after removing the companion:
https://github.com/GeriLife/companionship-care/blob/d7cdcdc1a37e5bd08f9c7b6a26a8116b9571ce5e/project/people/views.py#L154

**Comment by ritikBhandari** [comment]
Hi,
This issue looks good for my level. Can I work on this if not urgent?

**Comment by brylie** [comment]
@ritikBhandari, sure thanks! I'll assign you. I can also provide some guidance on the task.

**Comment by ritikBhandari** [comment]
So eventually we have to solve #24 right?

**Comment by brylie** [comment]
I've updated the issue description with a specification to clarify the intent and some code examples that could be useful to follow.

**Comment by brylie** [comment]
@ritikBhandari, yes, #24 is related to this issue. We can include this issue as part of #24 or handle them separately if desired. What would be your recommendation?

**Comment by ritikBhandari** [comment]
I guess we can include this issue as part of #24 since it is part of the UI settings proposal and we can have a clarity on what all tasks have been completed from the same #24

**Comment by ritikBhandari** [comment]
> I've updated the issue description with a specification to clarify the intent and some code examples that could be useful to follow.

Yup this is quite good. Atleast provides a fair ground on where to start resolving from.

**Comment by brylie** [comment]
OK, there is also a pattern we can follow with the modal dialogue for #24

The modal dialogue will basically have three action buttons:
- cancel - closes the dialogue without any action
- save - saves changes to the `Companion` instance
- delete - removes the `Companion` instance

I'm a bit concerned about deleting the `Companion` instance without any confirmation, but don't want to overcomplicate the task(s).

**Comment by ritikBhandari** [comment]
If we can cancel the dialogue and click the `back` button, we dont need to add a `delete` one and over-complicate things. What do u think?

**Comment by ritikBhandari** [comment]
And if we really want to `delete` the existing instance, we should create the button in the main window rather than having it in modal dialogue.

**Comment by brylie** [comment]
Yes, let's just create the button on the main view for now with a confirmation modal. We can improve the user experience later if needed.

**Comment by ritikBhandari** [comment]
> Yes, let's just create the button on the main view for now with a confirmation modal. We can improve the user experience later if needed.

`delete` one right?

**Comment by brylie** [comment]
Yes. The user flow would be:

1. click "delete" button on Companion card
2. display a modal "Are you sure you want to delete this companion?"
    - clicking "no" dismisses modal
3. clicking "yes", links to `DeleteCompanionView` with logic described above

**Comment by ritikBhandari** [comment]
That's cool!
