### ISSUE TITLE
Caregiver notifications (MVP)

### ISSUE THREAD

**Issue by brylie** [GeriLife/companionship-care#36]
We would like to send reminder notifications to caregivers so they remember the tasks they have agreed to take. These notifications can be:

- email
- text message
- mobile-app notification
- a combination of the above

## Task
- [ ] determine which type(s) of notifications to support initially
- [ ] research how to implement the related notifications using Django and other related services
- [ ] document the desired design
- [ ] indicate which notification type(s) might be added later in the roadmap by creating relevant GitHub issue(s)
- [ ] implement the initial notifications
