### ISSUE TITLE
Initial mobile notification app (Android and iOS with Flutter)

### ISSUE THREAD

**Issue by brylie** [GeriLife/companionship-care#37]
Related to #36 

We want to create a minimum-viable notification app that runs on mobile devices (Android and iOS). The application should, at a minimum, display a notification text to remind the user of the tasks for which they are responsible. The notification should be scheduled and delivered on a timely basis. Notifications should be created by the "backend" app and somehow scheduled on or delivered to the mobile app.

## Task
- [ ] research options for mobile notifications (using Flutter and related notification services)
- [ ] document the findings and choose an initial architecture
- [ ] create an initial Flutter app with example notification UI/UX (e.g. an app screen with a message and confirmation button)
- [ ] extend the Flutter app to support scheduled/overlay notifications
- [ ] develop the related backend notification architecture including integration with external service(s)
- [ ] integrate the Flutter app with the backend, making changes as necessary on both codebases
