### ISSUE TITLE
Set up project localization

### ISSUE THREAD

**Issue by brylie** [GeriLife/companionship-care#52]
We want to support multiple languages. There are several steps we need to complete in order to enable project localization.

## Task

- [x] ensure all current templates/code have good internationalization coverage
    - templates
    - views
    - models
    - forms
- [x] generate language file(s) for initially supported language(s)
- [x] add a language chooser widget to the navigation menu
- [x] Set up a project on POEditor so we can translate the UI texts for this project. Initial languages may include:
    - [x] Finnish
    - [ ] Dutch?
