### ISSUE TITLE
Add password-reset feature

### ISSUE THREAD

**Issue by brylie** [GeriLife/companionship-care#55]
Currently, if a user forgets their password they cannot request a password reset.

## Task

- [x] determine possible solutions for a password reset flow (email-based)
- [x] choose the best solution given the known trade-offs
- [x] implement the password reset feature

**Comment by Marsh-sudo** [comment]
Assign me this kindly

**Comment by Marsh-sudo** [comment]
Also it would be helpful if you could tell me which folder to concentrate on cause there are so many to navigate kindly

**Comment by brylie** [comment]
Thanks, @Marsh-sudo! :-)

See the `accounts` app for templates related to authentication.

- https://github.com/GeriLife/companionship-care/tree/main/project/accounts/templates/registration

For what it's worth, we may only need to define the following templates since Django auth already provides the default logic.

- registration/password_reset_form.html (displays the reset form to the user)
- registration/password_reset_complete.html (for the confirmation message before change)
- registration/password_change_done.html (once a password is successfully changed)

For now, we can use the following configuration for the email backend in `core/settings.py`

```py
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
```

**Comment by Marsh-sudo** [comment]
Is it okay i use the main branch to push the new project cause its easy for
you to intergrate it faster with the app itself

**Comment by brylie** [comment]
Closed by #75
