### ISSUE TITLE
Set up CI to run tests on commits

### ISSUE THREAD

**Issue by brylie** [GeriLife/companionship-care#59]
We don't currently run any CI jobs to verify that commits pass tests, for example.

## Task

- [ ] set up a GitHub action to run the following on commits
    - [ ] project tests
    - [x] lint / formatting check (black and autopep8)

TODO:

- [ ] rename `format` pipeline to `lint` (since it is only checking lint)
- [ ] move `autopep8` check from `test` pipeline to `lint`
- [ ] run `pytest` unit tests in `test` pipeline (since they are the actual tests)
- [ ] optional, add test coverage report #62 

Alternatively
- [ ] rename `format` to `lint_and_test` with a useful alias like "Lint and test"
- [ ] move the `autopep8` task to `lint_and_test`
- [ ] run `python project/manage.py test` in `format_and_test` as a job called `test`
- [ ] remove the separate `test` flow, since it contains redundant steps

At some point, we may look into more efficient use of these runners. For now, a single runner is fine, since they share dependencies.

**Comment by brylie** [comment]
@TheMythologist has kindly contributed code that runs linting tasks.

Next, we will run the project tests, via pytest, during CI.

As a follow-up, we will add a test coverage report #62
